spring:
# 配置数据源信息
  datasource:
# 配置数据源类型
      type: com.zaxxer.hikari.HikariDataSource
# 配置连接数据库信息
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mybatis_plus?serverTimezone=UTC
      username: root
      password: 123456
